### ISSUE TITLE
"Timestamp file does not exist"

### ISSUE THREAD

**Issue by N3ox1s** [Valentin-Metz/TwitchDropsMiner#60]
I keep getting Timestamp file does not exist on startup of the container. This causes the script to not even load up

**Comment by Valentin-Metz** [comment]
Is this still an issue?

**Comment by N3ox1s** [comment]
I tried to manually create a Timestamp file, but it then got stuck on starting the script up. Maybe I'm doing something wrong, I just deployed it via the command from the dockerfile that is suggested

**Comment by Valentin-Metz** [comment]
You shouldn't have to create it. It should automatically be created within the container only. There appear to be some upstream issues currently though, so maybe wait until the next release and see if the issue persists.

**Comment by N3ox1s** [comment]
Ill check again then and keep you posted.

**Comment by Valentin-Metz** [comment]
Upstream fix is out. It should work now.

**Comment by N3ox1s** [comment]
sadly it still doesnt create the timestamp file on my end. Tried recreating the whole container and repulling the image

**Comment by Valentin-Metz** [comment]
Can you provide the stdout logs of the container?

**Comment by N3ox1s** [comment]
[_twitch_drops_miner_logs.txt](https://github.com/user-attachments/files/15764863/_twitch_drops_miner_logs.txt)

**Comment by Valentin-Metz** [comment]
Are you sure that your config and cache file are mounted correctly? - Because that miner is not doing much and the timestamp file is created on drop progress.

**Comment by N3ox1s** [comment]
yes they are mounted correctly and show up in the host volume

**Comment by N3ox1s** [comment]
Maybe its a specific problem with my docker installation but so far i didnt face any other issues, so its quite weird. Maybe if somebody else faces a similar issue we might be able to resolve it as i dont think there are any other ways to debug this.

**Comment by Valentin-Metz** [comment]
Try the following: delete all config and cache files and re-create them from a GUI instance of the program (start with a fresh clone from master).
Then move them over (never re-use the login cookies), mount them and paste the exact docker command you used here.

**Comment by N3ox1s** [comment]
Manually adding all the files did the trick. I noticed that they all showed up as directories on the host machine. By repacing them everything seems to work now. Timestamp got created as well. Thanks for the help. Still kinda weird how that happened

**Comment by Valentin-Metz** [comment]
My guess would be that you were perhaps in the wrong folder (current working directory) when creating the container.
If files do not exist at the relative location Docker expects them, it'll simply create and link in empty directories.
Always nice to be able to help!
